"""empty message

Revision ID: 505e09436c4d
Revises: 8a240c5e633c
Create Date: 2019-12-07 17:29:55.954295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505e09436c4d'
down_revision = '8a240c5e633c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    op.add_column('todo', sa.Column('statusShare', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'statusShare')
    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('friend_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
